services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: docker-code
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
      - PASSWORD=${PASSWORD}
      - HASHED_PASSWORD=${HASHED_PASSWORD:-}
      - SUDO_PASSWORD=${SUDO_PASSWORD:-${PASSWORD}}
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH:-}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE:-/config/workspace}
      - DOCKER_MODS=${DOCKER_MODS:-"linuxserver/mods:universal-docker"}
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ${FOLDER}:/data
    ports:
      - "${PORT:-8443}:${PORT:-8000}"